# Generated by Django 3.0.7 on 2020-06-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urlshort_db',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('long_url', models.CharField(max_length=600)),
                ('shorted_url', models.CharField(max_length=50)),
            ],
        ),
    ]
