# Generated by Django 3.0.7 on 2020-06-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='urlshort_db',
            new_name='urlshortdb',
        ),
    ]
