# Generated by Django 3.0.7 on 2020-06-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0002_auto_20200610_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortdb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
